# Generated by Django 2.2.1 on 2019-05-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remote_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remote_post',
            name='published_date',
        ),
    ]
