# Generated by Django 2.2.1 on 2019-05-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190531_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote_post',
            name='text',
            field=models.TextField(),
        ),
    ]
